# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('name',), 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ('name',), 'verbose_name_plural': 'Fabrics'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('name',), 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'verbose_name_plural': 'Units'},
        ),
    ]
