# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_discount_purchaseorder_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ('id',)},
        ),
    ]
