# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_balance_amount_invoice_discount_invoice_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
