# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('product', 'color', 'size')},
        ),
    ]
