# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_discount_salesorder_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'ordering': ('id',)},
        ),
    ]
